# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f24d9dc1039de8da641961f5bde0e52"
name = "Gold Price Ticker"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/api/proxy"
subpath = "gold-ticker"
prefix = "apps"
